### ISSUE TITLE
Authenticity of checksum file can not be assured! nodejs 10.15.1

### ISSUE THREAD

**Issue by mauricionr** [asdf-vm/asdf-nodejs#119]
NodeJS 10.15.0 works fine!

```
users-MacBook-Pro:user user$ asdf install nodejs 10.15.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4229    0  4229    0     0    362      0 --:--:--  0:00:11 --:--:--  1236
gpg: Signature made Tue Jan 29 16:43:29 2019 -02
gpg:                using RSA key B9E2F5981AA6E0CD28160D9FF13993A75599653C
gpg: Can't check signature: No public key
Authenticity of checksum file can not be assured! Please be sure to check the README of asdf-nodejs in case you did not yet bootstrap trust. If you already did that then that is the point to become SUSPICIOUS! There must be a reason why this is failing. If you are installing an older NodeJS version you might need to import OpenPGP keys of previous release managers. Exiting.
users-MacBook-Pro:user user$
```

**Comment by Stratus3D** [comment]
Closing since you need to have the release team keys imported before installing.

**Comment by hubertlepicki** [comment]
I am having the same issue @Stratus3D as @mauricionr . Installing current or previous keyring does not help.

`$ bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring         
gpg: key 7434390BDBE9B9C5: 3 signatures not checked due to missing keys
gpg: key 7434390BDBE9B9C5: "Colin Ihrig <cjihrig@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key 09FE44734EB7990E: 5 signatures not checked due to missing keys
gpg: key 09FE44734EB7990E: "Jeremiah Senkpiel <fishrock123@rocketmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key C97EC7A07EDE3FC1: 19 signatures not checked due to missing keys
gpg: key C97EC7A07EDE3FC1: "keybase.io/jasnell <jasnell@keybase.io>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key C273792F7D83545D: 4 signatures not checked due to missing keys
gpg: key C273792F7D83545D: "Rod Vagg <rod@vagg.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key E73BC641CC11F4C8: 14 signatures not checked due to missing keys
gpg: key E73BC641CC11F4C8: "Myles Borins <myles.borins@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key B63B535A4C206CA9: 9 signatures not checked due to missing keys
gpg: key B63B535A4C206CA9: "Evan Lucas <evanlucas@me.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key 770F7A9A5AE15600: "Michaël Zasso (Targos) <targos@protonmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key B01FBB92821C587A: "Gibson Fahnestock <gibfahn@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

$ asdf install nodejs 11.15.1                                
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7041    0  7041    0     0  10668      0 --:--:-- --:--:-- --:--:-- 10652
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
Authenticity of checksum file can not be assured! Please be sure to check the README of asdf-nodejs in case you did not yet bootstrap trust. If you already did that then that is the point to become SUSPICIOUS! There must be a reason why this is failing. If you are installing an older NodeJS version you might need to import OpenPGP keys of previous release managers. Exiting.
`

@mauricionr is this what your issue is too?

**Comment by hubertlepicki** [comment]
@Stratus3D I have the same issue. Importing keyrings does not help, either current nor previous.

10.15.0 installs correctly. 10.15.1 does not.

**Comment by shvetsovdm** [comment]
Try to update asdf-nodejs plugin itself first and then update release keys:

```
asdf plugin-update nodejs
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
```

**Comment by kuldeepaggarwal** [comment]
@Stratus3D I have the same issue. Importing keyrings does not help, neither current nor previous.

10.15.2 installs correctly. 10.15.3 does not.

**Comment by denizdogan** [comment]
Would it be possible to have asdf ask the user for confirmation and then installing the keyring automatically?

**Comment by levicole** [comment]
@Stratus3D I too have the same issue. 10.15.3 is not installing correctly after importing keyrings and updating the plugin.

**Comment by pvinis** [comment]
I feel this https://github.com/asdf-vm/asdf-nodejs/issues/119#issuecomment-459760160 should be printed on the error in the terminal. Either link here or directly print the command we need to run.

**Comment by nobleach** [comment]
That'll work... until one gets `gpg: keyserver receive failed: Server indicated a failure`
