### ISSUE TITLE
Unable to install node 11.10.1

### ISSUE THREAD

**Issue by SRGOM** [asdf-vm/asdf-nodejs#125]
I'm creating a new issue to get some kind help here since i am unable to resolve this. My issue is a copy of https://github.com/asdf-vm/asdf-nodejs/issues/82  for v 11.10.1

My problem is key verification. I'm on Arch Linux if it matters.

**Comment by Stratus3D** [comment]
We are probably missing a key from the release team. Adding it to the `import-release-team-keyring` script should fix the issue. We will need to create a PR for this once we've figured out what key is missing.

**Comment by SRGOM** [comment]
This is the release key section. https://github.com/nodejs/node#release-keys

How can I help?

**Comment by dgmcguire** [comment]
running 
`gpg --keyserver pool.sks-keyservers.net --recv-keys A48C2BEE680E841632CD4E44F07496B3EB3C1762`

fixes this issue for me - of course if you're more security conscious than me you'll want to checkout exactly who you're trusting

**Comment by Stratus3D** [comment]
I needed to run `gpg --keyserver pool.sks-keyservers.net --recv-keys B9E2F5981AA6E0CD28160D9FF13993A75599653C` in order to install `10.15.1`. I need to go back and compare our list of keys with the list of keys in the Node.JS readme.

**Comment by sukima** [comment]
I am getting key server errors attempting to receive `A48C2BEE680E841632CD4E44F07496B3EB3C1762`. I've sent an email to Ruben Bridgewater (the owner of that key) in hopes there may be an alternative location for the key.

**Comment by sevenseacat** [comment]
I needed to `gpg --keyserver pool.sks-keyservers.net --recv-keys 4ED778F539E3634C779C87C6D7062848A1AB005C` to get Beth Griggs' signature, to install 10.15.3.

**Comment by SRGOM** [comment]
I feel like a systematic solution rather than ad-hoc solutions would probably make a lot of sense. Closing this in the hope that somebody will work towards it.

**Comment by sukima** [comment]
@SRGOM There is no systemic solution when the authors of Node are unable to publish their public keys. The problem here exists because Node is signed by developers who did not publish their public keys for verification. Or there was a problem with the key server.

If there was a solution it would likely involve asdf-node pinning public keys (including them with the repo instead of downloading them via bash script) but this would introduce a maintenance nightmare.

I think the reports here were in hopes that asdf-node might have more clout to talk to Node developers then an average person. For example I emailed the offending developer who incorrectly published their public key and never received a response. When this scenario happens the only solution is to use `NODEJS_CHECK_SIGNATURES=no`.

Since this issue is closed is there another place to track ideas from others?

**Comment by Stratus3D** [comment]
This looks like a similar issue that is still open: https://github.com/asdf-vm/asdf-nodejs/issues/128

I'm open to any suggestions you all have, but I think this is a problem that is best solved upstream by the Node maintainers.
