### ISSUE TITLE
XCode messes with PATH, fails to find node

### ISSUE THREAD

**Issue by aloukissas** [asdf-vm/asdf-nodejs#203]
More of an FYI than an issue.

My xcode build for a react-native project was failing because it couldn't find `node` in the `PATH` and then I realized why. It rewrites PATH, ignoring anything added to your rc files by asdf. In my case, this is what xcode did:

`export PATH\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

Maybe there's a way to asdf install globally (e.g. to `/usr/local`) - but I haven't looked into this yet.

**Comment by cho-m** [comment]
Did you source your `asdf` environment (or your rc files) inside XCode (online resources recommend XCode Run Script phase)?

Shell config files are only sourced for particular invocations of the shell.
IDEs like XCode may or may not set up shell env depending on exact operation/settings.

If a shell is invoked, then it is usually non-interactive and may also be non-login since combination is common for a program calling another program.

e.g. Some common shell config files:
| file | invocation | shell |
| --- | --- | --- |
| `.profile` | interactive + login | `sh` (and `bash`  if `.bash_profile` doesn't exist) |
| `.bash_profile` | interactive + login | `bash` |
| `.bashrc` | interactive + non-login | `bash` |
| `.zshrc` | interactive | `zsh` |
| `.zlogin`/`.zprofile` | login | `zsh` |
| `.zshenv` | all | `zsh` |

**Comment by augustobmoura** [comment]
I don't have a macOS so I cannot give any answer outside of some guesses, but if XCode really overrides the PATH variable it should have a configuration so that you can customize it for your use, if that is the case just adding `$ASDF_DIR/shims` to it should solve the issue, note that ASDF_DIR should be replaced by your installation path.

**Comment by augustobmoura** [comment]
Closing this, because is related to a XCode configuration problem, not a real issue of asdf-nodejs
