### ISSUE TITLE
Support global NPM installs between Node versions

### ISSUE THREAD

**Issue by ndarilek** [asdf-vm/asdf-nodejs#22]
Today I upgraded from Node 6.7 to 6.8, and now my global NPM installations all say something like:

```
No such command in 6.8.0 of nodejs
```

There's no reason that my NPM modules need to be limited to the Node version that installed them. Can the commands they install not stay intact? I thought a `asdf reshim nodejs` would do it but apparently not. Am I missing something?

**Comment by muhifauzan** [comment]
I also have something similar, but it's clean install. I got this error
![image](https://cloud.githubusercontent.com/assets/14904191/21143569/d10a33aa-c179-11e6-803e-fba92eab61bf.png)

**Comment by muhifauzan** [comment]
Another screenshot related to comment above. This one is not about npm, but about the node itself.

![image](https://cloud.githubusercontent.com/assets/14904191/21143775/8fc86af0-c17a-11e6-8fd4-31af740a3f39.png)

I'm sorry if this is the problem from my configuration, I'm pretty new to this stuff.

**Comment by muhifauzan** [comment]
Ah, my bad. Actually, I'm at fault here. I'm cloning the `master` current `HEAD` instead of the branch `v0.2.0`. I'm sorry

**Comment by Zanadar** [comment]
I'm actually having this same issue.  When I upgrade NPM on one version of node `v4.4.5 and npm@3`, and then swap node versions `v6.1.0`, then swap back, somehow the npm version in the `v.4.4.5` install goes back to `v2.15.5`.

**Comment by sethetter** [comment]
Having the same issue here. Any help?

**Comment by sublimecoder** [comment]
Having the same issue NPM "command not found" after installing with asdf

**Comment by joemsak** [comment]
I am unable to use global packages on older versions of nodejs same as @stefanfrede

**Comment by Stratus3D** [comment]
@ndarilek is this still an issue?

**Comment by jeffryang24** [comment]
Hmm... just a question do asdf support migrating global packages into the new nodejs installation, such us: `nvm install node --reinstall-packages-from=node` in `nvm`. For example: I installed `eslint` globally in node 8.15.1, then I install the node 12.14.1 and set node 12.14.1 as current global version. Currently, the `eslint` bin only exists on 8.15.1, but not on the new 12.14.1... :bowing_man:

**Comment by jeffryang24** [comment]
cc: @Stratus3D. Here's my result.

asdf-vm: `v0.7.8-4a3e3d6`
asdf-nodejs: `cd8dc32e82507a229fe90c0b01d1089a3ac6844c`
nodejs: v12.16.2

### Plan/Execution Step

I have `create-next-app` global cli in nodejs v12.16.2 LTS. Now, I want to upgrade my nodejs to v12.18.3 LTS. After that, I expect that the `create-next-app` still available while I have upgraded the node to v12.18.3 LTS.

1. Check `node --version` -> `v12.16.2`.
2. Install `create-next-app` as global cli using `npm install -g create-next-app`.
3. Run `asdf reshim nodejs`.
4. Check `create-next-app` has bee listed using `npm ls -g --depth=0`.
5. Update asdf-nodejs plugin using `asdf plugin update nodejs`.
6. Install nodejs 12.18.3 LTS by using `NODEJS_CHECK_SIGNATURES=no asdf install nodejs 12.18.3` (I need to bypass the signature checking since my gpg setting doesn't allow weak digest).
7. Ensure nodejs 12.18.3 has been installed by using `asdf list nodejs | grep 12.18.3`.
8. Change global nodejs version to 12.18.3 by using `asdf global nodejs 12.18.3`.
9. Run reshim again `asdf reshim nodejs`.
10. Ensure nodejs has been upgrade by using `node --version` -> `v12.18.3`.
11. Check `create-next-app` cli is still available while upgrading to nodejs 12.18.3 by using `npm ls -g --depth=0`.

### Expected Behavior

`create-next-app` is still available in node v12.18.3.

### Actual Behavior

`create-next-app` is not available in node v12.18.3.

```bash
➜ npm ls -g --depth=0
/home/jeffryangtoni/.asdf/installs/nodejs/12.18.3/.npm/lib
└── (empty)
```

Probably asdf need to support this feature from `nvm`? `nvm install node --reinstall-packages-from=node` :bow:

**Comment by dustypomerleau** [comment]
@Stratus3D This is definitely an ongoing issue. With Homebrew, the path to global node modules doesn't change between updates, as it's kept in a separate location (`/usr/local/lib/node_modules`). But in asdf, the path is something like:

```
/Users/my_user/.asdf/installs/nodejs/14.11.0/.npm/lib/node_modules
```

Since it's namespaced by the version number, we lose access to globally installed modules on every update of node.

**Comment by augustobmoura** [comment]
There are some traps around sharing global installs between node versions, mostly incompatibilities, some packages only support specific node versions, other need to be *build* against a specific version (node-sass is famous for doing it for maximum performance).

If you ever share the packages between versions you need to be aware that depending on the context you are, in a project with a different node version than your global installation for example, your global commands might not work and you will get errors, `npm` itself is a global installed package that **needs** specific node versions and might not work in different contexts.

As of now you can have a command in installed all versions by setting up [default npm packages](https://github.com/asdf-vm/asdf-nodejs/tree/b38dda3594af967f632c94babea60f506334b753#default-npm-packages) that are installed automatically after every `asdf install nodejs $version`. A nice oneliner for installing a global command in every version is:

``` bash
npm_install_all_versions() {
  for pkg; do
    asdf list nodejs | xargs -n1 -I{} env ASDF_NODEJS_VERSION="{}" npm install -g "$pkg"
  done  
} 

npm_install_all_versions npm typescript tldr
```

After making that clear, I totally think that is possible to have a global and version specific installations utilizing of path priority and the prefix npm config that might amenize this problem. I will look into something this week
