### ISSUE TITLE
Major version shorthand values are not supported for .nvmrc

### ISSUE THREAD

**Issue by handreistoicescu** [asdf-vm/asdf-nodejs#235]
`.nvmrc` files support shorthand major version numbers, such as a simple `12`. This means nvm should use the latest version of Node.js 12.x.

If asdf is configured with `legacy_version_file = yes`, and the user tries a simple `node -v`, they get:

```bash
No preset version installed for command node
Please install a version by running one of the following:

asdf install nodejs 12

or add one of the following versions in your config file at /Users/andrei/.tool-versions
nodejs 12.18.4
nodejs 12.10.0
nodejs 12.18.3
nodejs 14.15.4
nodejs 14.16.1
```

If the user then tries to run `asdf install nodejs 12`, they get:

```bash
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10855    0 10855    0     0  50724      0 --:--:-- --:--:-- --:--:-- 50724
Checksum not found for version 12
```

Which is normal, because there is no version `12` when one runs `asdf list all nodejs 12`:

```bash
12.0.0
12.1.0
12.2.0
...
12.21.0
12.22.0
12.22.1
```

If this problem would be fixed, there would be better compatibility with the various ways `.nvmrc` is used in the wild, and everything would be just 🌈✨🌼

I really hope this gets fixed! Thanks for your amazing work on this repo!

**Comment by jthegedus** [comment]
@Stratus3D correct me if I am wrong, but `legacy_version_file` was meant as a migration path to `.tool-versions` not an agreement that we would support all behaviours of the other version manager systems.

**Comment by Stratus3D** [comment]
> @Stratus3D correct me if I am wrong, but `legacy_version_file` was meant as a migration path to `.tool-versions` not an agreement that we would support all behaviours of the other version manager systems.
> 
> I know `asdf` core is currently aimed at being **exact** versions with version range support not currently on the horizon.

The legacy version file feature is intended to work indefinitely, but only in ways that are compatible with asdf. For example, asdf requires that exact version numbers be specified. asdf doesn't handle version ranges or ambiguous versions. Special versions like `latest` are resolved at the time the asdf command specifying them is run and are not permitted to in `.tool-versions`  because of the nondeterminism they would introduce. We don't want to allow any variability in versions specified in any of the version files that asdf supports because we want asdf to be **deterministic**. We don't want a new version release to accidentally pull the rug out from under someone because they had specified a shorthand version or version range. **This constraint allows us to provide stronger guarantees about asdf behavior.** If a user desires a project to always be updated to the latest version of some tool, there is nothing preventing someone from setting up a dependabot-like tool to automatically bump versions specified in `.tool-versions`.

In the case of this ticket, the shorthand version cannot be supported. Either the `.nvmrc` will need to specify an absolute nodejs version or the project will need to be migrated to use `.tool-versions`. 

Sorry @handreistoicescu , but this isn't a bug and won't be fixed.

**Comment by handreistoicescu** [comment]
@jthegedus @Stratus3D 

Thanks for your ellaborate answers! I've understood the reasoning behind this now.

Closing this issue.

**Comment by Drarok** [comment]
I understand this is a design decision, but I think the error message "Checksum not found for version 14" is misleading and not at all useful. It's taken me ages to find out why this commonly-used feature doesn't work, and leaves an unsatisfactory taste in the mouth.

> It is like gvm, nvm, rbenv & pyenv (and more) all in one! Simply install your language's plugin!

I feel the project as a whole is mis-sold right here.

**Comment by Stratus3D** [comment]
PR welcome @Drarok !

**Comment by codethief** [comment]
@Stratus3D

> We don't want to allow any variability in versions specified in any of the version files that asdf supports because we want asdf to be deterministic. We don't want a new version release to accidentally pull the rug out from under someone because they had specified a shorthand version or version range.

I totally understand this argument and support your goal but, given that the meaning of something like `nodejs lts-fermium` might change over time (due to new minor/patch releases, compare https://github.com/asdf-vm/asdf-nodejs/issues/273), I'm not sure this goal is being achieved right now.

**Comment by Diluka** [comment]
```
# .nvmrc
22
```

```
$ node -v
No version is set for command node
Consider adding one of the following versions in your config file at
nodejs lts
nodejs 22.22.3
```

### BUT `asdf latest` can parse major to a specific version
```
$ asdf latest nodejs 22
22.22.3
```
