### ISSUE TITLE
The shim template has no backward compatibility with older versions of asdf-core

### ISSUE THREAD

**Issue by Fumipo-Theta** [asdf-vm/asdf-nodejs#252]
I am using asdf v0.5.1.
Running npm fails with the latest version of plugin (https://github.com/asdf-vm/asdf-nodejs/commit/95a2091f7b64497c002dc709b267f5d03f302498).  

I think [the logic](https://github.com/asdf-vm/asdf-nodejs/blob/95a2091f7b64497c002dc709b267f5d03f302498/shims/npm#L18) to find real binary in the new shim template will work only with asdf >= v0.7.0.
I checked with some version of asdf on a clean AmazonLinux2 as below:

```sh
$ sudo yum install -y git
$ git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch vX.Y.Z
$ echo ". $HOME/.asdf/asdf.sh" >> ~/.bashrc
$ source ~/.bashrc
$ asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
$ asdf install nodejs 14.17.1
$ echo "nodejs 14.17.1" > ~/.tool-versions
$ npm -v
# OK if the version is shown
```

The results are:
- asdf v0.5.1 => NG
- asdf v0.6.3 => NG
- asdf v0.7.0 => OK
- asdf 0.8.1 => OK

With the NG version, the `PATH` [here](https://github.com/asdf-vm/asdf-nodejs/blob/95a2091f7b64497c002dc709b267f5d03f302498/shims/npm#L18) is below:

```
/home/ec2-user/.asdf/shims:/home/ec2-user/.asdf/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin
```

Is it possible to maintain backward compatibility with older versions?
Or just adding compatibility information would be better :-).

**Comment by augustobmoura** [comment]
Yes, asdf-nodejs doesn't support asdf-core versions older than 7.0. I don't think we need to add information about compatibility because before the official v1.0.0, asdf-core will be adding many new features that could get used by the plugins, and retro compatibility is not a requirement right now. As a rule of thumb, before you update or add any plugin, you should always update asdf-core (at least until asdf 1.0 is out).

On the other hand, about adding some retro compatibility, even though it is not our focus right now, it is always desirable if it doesn't get in the way of functionality. I'm currently developing a feature that might add support for these older versions.

**Comment by Fumipo-Theta** [comment]
Thank you for your reply and future vision.
I understand and agree with the support concept.
