### ISSUE TITLE
npm silently fails

### ISSUE THREAD

**Issue by grepsedawk** [asdf-vm/asdf-nodejs#258]
When running the npm shim, it silently fails.
It fails due to this line:
https://github.com/asdf-vm/asdf-nodejs/blob/master/shims/npm#L19

It fails because it can't find a suitable `npm` (without the shims directory)

**Comment by grepsedawk** [comment]
Reverting to ea133489c676e60300d4f9c35319d1f3405b13b2 and running `asdf reshim nodejs` does the trick here

**Comment by augustobmoura** [comment]
Are you calling the asdf shim (`$ASDF_DIR/shims/npm`) or the plugin shim directly (`$ASDF_DIR/plugins/nodejs/shims/npm`)? You need to call the asdf shim because asdf adds the real binary to PATH, making it run standalone is a good idea though

https://github.com/asdf-vm/asdf-nodejs/commit/ea133489c676e60300d4f9c35319d1f3405b13b2 will work but you might have some issues with auto reshimming on global installs in new node versions

**Comment by grepsedawk** [comment]
I am calling the asdf shim

**Comment by augustobmoura** [comment]
It should be working on master right now

@grepsedawk can you check if the issue is solved?

**Comment by grepsedawk** [comment]
Yep all good, ty
