### ISSUE TITLE
Use specific version of npm per project?

### ISSUE THREAD

**Issue by jrnail23** [asdf-vm/asdf-nodejs#266]
Hi,
We've got a number of projects using the same node version, and presuming to use the same (default) npm major rev (v6).  However, one of our projects has upgraded to npm v7, to use its new workspaces feature, while still on the same node version as the others.
Is there a way I can set up asdf to use the default (v6) for my projects, but then configure that one project to use v7?

**Comment by augustobmoura** [comment]
I think your best option is using a wrapper around `npx` (something like `alias npm="npx npm"`), `npx` tries to resolve the version of the current `package.json`, and if it is not defined it tries to install the latest version available. In that case if you define a `devDependency` in your project's package.json to npm 6 or lower, it should work fine for day-to-day command line work. However, be advised that scripts or others tools that call npm directly will not see the alias and mostly likely fall back to the global npm installation.

Another option is to mess with the PATH variable when entering the project's directory, something probably using [`direnv`](https://direnv.net/). You can create a simple `.envrc` that adds `./node_modules/.bin` to the path. You will also need to have `npm` on the project's `package.json` for this to work:

``` bash
# .envrc file
export PATH="$PWD/node_modules/.bin:$PATH"
```

I'm closing this right now because this is more of a general `npm` issue. Even though it would be cool to have independently versioned commands is probably not feasible with current `node`/`npm` setups, for how global installations work. If anything this should be discussed at `asdf-core` as a feature for every other plugin.
