### ISSUE TITLE
Allow comments in default packages

### ISSUE THREAD

**Issue by erikw** [asdf-vm/asdf-nodejs#280]
It's lovely that we have the `$ASDF_NPM_DEFAULT_PACKAGES_FILE` file. However there's just a small thing that prevents it full potential from being used.

It's important to be able to document on why I need a package (easy to forget when coming back to it after a while). Thus allowing for blank lines and `# comment` lines would be a very neat addon to have!

`asdf-ruby` has support for blank and comment lines already:
https://github.com/asdf-vm/asdf-ruby/blob/c6db9a376d1b01af9a5028f11fdfb96ab8902d60/bin/install#L100-L104

(this ticket is analogous to https://github.com/danhper/asdf-python/issues/105)

**Comment by jsejcksn** [comment]
(#172 precedes this issue, but is a subtype that would be covered by a fix for this one)

The relevant loop is here:

https://github.com/asdf-vm/asdf-nodejs/blob/ed343553166813b1ca37a187e44779659cd33ca2/bin/install#L101-L112

A possible fix would be to create a function `is_invalid_package_name` to determine whether a line (`$name` in the loop) meets one of the following criteria:
- length `0`
- only whitespace
- the first non-whitespace character is the comment token `#`

If a criterion is met, return `0`, otherwise return `1`.

Then wrap the current loop body in an if...else statement, [using the function as the condition](https://stackoverflow.com/q/8117822/438273), and in the true branch, just `continue` to the next iteration.

I haven't written a shell script in years, so I can't provide an example with actual syntax.

**Comment by augustobmoura** [comment]
I will try to work on it. We could also simplify the way the script is working to a single `npm install -g <packages...>` instead of looping and installing one by one

**Comment by jsejcksn** [comment]
> We could also simplify the way the script is working to a single `npm install -g <packages...>` instead of looping and installing one by one

@augustobmoura There might be a good reason that they're being installed individually. (But I don't know for sure.)

_FYI: That's also how [`volta`](https://github.com/volta-cli/volta) does it._

**Comment by augustobmoura** [comment]
The only problem I could possibly think of is that if installing multiple packages and, for some reason, one of the installations fails, all the other packages will rollback and not be installed. In my opinion we should allow that, the user should be responsible for broken packages being installed by default

**Comment by erikw** [comment]
Thank you!
