### ISSUE TITLE
`python not found` error when attempting to install nodejs version

### ISSUE THREAD

**Issue by avery-brown-coalition** [asdf-vm/asdf-nodejs#302]
Summary: Attempting to install another version of nodejs is resulting in the following error

```bash
front-end on  master [$!] via  ❯ asdf install nodejs 12.22.12
Trying to update node-build... ok
Downloading node-v12.22.12.tar.gz...
-> https://nodejs.org/dist/v12.22.12/node-v12.22.12.tar.gz

WARNING: node-v12.22.12 is in LTS Maintenance mode and nearing its end of life.
It only receives *critical* security updates, *critical* bug fixes and documentation updates.

Installing node-v12.22.12...

BUILD FAILED (OS X 12.3.1 using node-build 4.9.79-6-geddd35df)

Inspect or clean up the working tree at /var/folders/x_/km_r3gc925q2jdrdjmv17mdm0000gq/T/node-build.20220506120623.25020.9nxQmA
Results logged to /var/folders/x_/km_r3gc925q2jdrdjmv17mdm0000gq/T/node-build.20220506120623.25020.log
```

Log created

```
/var/folders/x_/km_r3gc925q2jdrdjmv17mdm0000gq/T/node-build.20220506120623.25020.9nxQmA ~/Documents/projects/my-project
/var/folders/x_/km_r3gc925q2jdrdjmv17mdm0000gq/T/node-build.20220506120623.25020.9nxQmA/node-v12.22.12 /var/folders/x_/km_r3gc925q2jdrdjmv17mdm0000gq/T/node-build.20220506120623.25020.9nxQmA ~/Documents/projects/my-project
./configure: line 3: exec: python: not found
```

Is a separate installing of python required for `asdf` or this plugin? I am not certain why it keeps trying to grab python.

**Comment by augustobmoura** [comment]
You are probably using a macOS with M1 right? Because M1 is kinda recent there are no pre-compiled binaries for it on older nodejs versions. In these cases, we fall back on building it from source, this is why python is needed (as well as [all other requirements for building it from source](https://github.com/nodejs/node/blob/master/BUILDING.md#building-nodejs-on-supported-platforms), note that different nodejs versions have different requirements). We have an explanation at https://github.com/asdf-vm/asdf-nodejs#use

If you have any other question or think that there any other bugs please comment below so that I can re-open the issue if needed

**Comment by avery-brown-coalition** [comment]
Perhaps you could update the README then? I don't see or have trouble finding an explanation of this on the page that you linked.

**Comment by avery-brown-coalition** [comment]
@augustobmoura I tried installing python3 as required by the node version but I am uncertain as to how to get nodejs to recognize that this has been installed

**Comment by augustobmoura** [comment]
> Perhaps you could update the README then? I don't see or have trouble finding an explanation of this on the page that you linked.

In this case, I think our docs are ok, we make it pretty clear that we fall back to compiling from source. But we definitely need some help on writing more docs, perhaps a specific section for macOS and M1. I think the information is too mixed with others. Contributions are welcome 😉

> @augustobmoura I tried installing python3 as required by the node version but I am uncertain as to how to get nodejs to recognize that this has been installed

Just having the executable on PATH should suffice

**Comment by josemigallas** [comment]
Hi, I am also trying to install node on a m1 Mac using asdf. According to the provided links, node-build supports python>=3. However I get the error `Please use Python 2.7` when running `asdf install`:
```
jgallaso@jgallaso1-mac porta % python --version
Python 3.10.6
```
```
jgallaso@jgallaso1-mac porta % asdf install
Trying to update node-build... ok
Downloading node-v12.22.5.tar.gz...
-> https://nodejs.org/dist/v12.22.5/node-v12.22.5.tar.gz

WARNING: node-v12.22.5 is in LTS Maintenance mode and nearing its end of life.
It only receives *critical* security updates, *critical* bug fixes and documentation updates.

Installing node-v12.22.5...

BUILD FAILED (OS X 12.5.1 using node-build 4.9.89)

Inspect or clean up the working tree at /var/folders/p6/_ghw1fpd7gqg7rkv236sf14c0000gn/T/node-build.20220902122156.39714.rmprqN
Results logged to /var/folders/p6/_ghw1fpd7gqg7rkv236sf14c0000gn/T/node-build.20220902122156.39714.log

Last 10 log lines:
/var/folders/p6/_ghw1fpd7gqg7rkv236sf14c0000gn/T/node-build.20220902122156.39714.rmprqN ~/projects/3scale/porta
/var/folders/p6/_ghw1fpd7gqg7rkv236sf14c0000gn/T/node-build.20220902122156.39714.rmprqN/node-v12.22.5 /var/folders/p6/_ghw1fpd7gqg7rkv236sf14c0000gn/T/node-build.20220902122156.39714.rmprqN ~/projects/3scale/porta
Please use Python 2.7
Missing or stale config.gypi, please run ./configure
make: *** [config.gypi] Error 1
```

Is this because I'm using node 12?

**Comment by augustobmoura** [comment]
Each node version has different build requirements. When building from source you need to provide all of them. You can see past building requirements on [nodejs docs](https://github.com/nodejs/node/blob/main/BUILDING.md#previous-versions-of-this-document)

Another way to do it is to install the x64 version instead of the M1 ARM, by running `arch -x86_64 asdf install nodejs <version>`.
We are currently having a dicusssion if we should fallback to x64 instead of trying to build from source. We are open to opinions on it.
