### ISSUE TITLE
Installing `lts` via `.tool-versions` (`asdf install`) is broken.

### ISSUE THREAD

**Issue by jimsynz** [asdf-vm/asdf-nodejs#319]
Hi there.

I ran into this problem while trying to build a devcontainer for a project, but it seems to happen wherever I try it.

Using a `.tool-versions` file and just running `asdf install` with no arguments:

```
$ echo "nodejs lts" > .tool-versions
$ asdf install
Cloning node-build...
node-build: definition not found: lts
```

whereas installing it explicitly works:

```
$ asdf install nodejs lts
Installing alias lts as 16.17.1
Trying to update node-build... ok
Downloading node-v16.17.1-darwin-arm64.tar.gz...
-> https://nodejs.org/dist/v16.17.1/node-v16.17.1-darwin-arm64.tar.gz
Installing node-v16.17.1-darwin-arm64...
Installed node-v16.17.1-darwin-arm64 to /Users/jmshrtn/.asdf/installs/nodejs/16.17.1

Linking "lts" to "16.17.1"
```

Thanks!

**Comment by Stratus3D** [comment]
All versions in the `.tool-versions` file must be absolute version numbers that do not change. Aliases like `lts` are not permitted. Aliases are not permitted because the data in `.tool-versions` must produce the same tools regardless of time and environment (e.g. it is deterministic). Aliases break this requirement.
