### ISSUE TITLE
Add subcommand which will output which version is currently LTS

### ISSUE THREAD

**Issue by onnimonni** [asdf-vm/asdf-nodejs#339]
Hey!

I saw LTS versions have been discussed already in #308 and there seems to be longer workaround in https://github.com/asdf-vm/asdf/issues/1024.

But I see that this plugin currently adds few subcommands to asdf:
```
$ asdf
...
PLUGIN nodejs
  asdf nodejs nodebuild
  asdf nodejs update nodebuild
```

Could we add a subcommand which would resolve the current lts version into version number?

I'm running a daily github action that will create pull request to my `.tool-versions` file to newer version whenever that is available.

Now without this alias I need to waste compute resources to install that nodejs into that github action before I can actually see what the version is.

If we would have a alias which would resolve the `lts` to the latest one then we wouldn't need to do that and the github action would be much faster 👍

**Comment by augustobmoura** [comment]
Hi @onnimonni :wave: 

That's a really good idea! I thought about it when I was implementing lts aliases but because it was not urgent I didn't finish it.

I'm having little time to do it right now, but we are open to contributions if you want to have a stab at it.

I think what we need to do is create a [command extension script file](https://asdf-vm.com/plugins/create.html#extension-commands-for-asdf-cli) that calls for `print_index_tab` and grep for the lts passed as argument, similar to how we do it on [install](https://github.com/asdf-vm/asdf-nodejs/blob/c9e5df443b932f22e79e178a52866b053065be80/bin/install#L76-L80). I can help with any questions you have
