### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by kemelzaidan** [asdf-vm/asdf-nodejs#395]
I have no idea on how to fix that, but no matter what version of Node.js I install, I can't run node because I always receive this message:

```sh
$ node --version
node: symbol lookup error: node: undefined symbol: _ZN6icu_738ByteSink15GetAppendBufferEiiPciPi
```

Any help will be appreciated!

**Comment by allisonphillips** [comment]
I'd hazard a guess that it's one of these things:
- The [installation instructions] weren't followed exactly, so when your computer tries to resolve `node` it finds a result for some other executable named node, either because it occurs earlier in PATH than ~/.asdf/shims or because .asdf/shims isn't in your PATH at all.
- The [installation instructions] were followed, but something else on your computer isn't configured to load the shims early in your search path or at all
- The node executable your computer is mapping the command to (whether it's the version installed with asdf-nodejs or some other random version) is bugged (google "node: symbol lookup error: node: undefined symbol:" for whatever node version you've installed)
- The root of the directory where you're running that command doesn't contain a .tool-versions folder with some `nodejs SEMANTIC_VERSION` line defining which SEMANTIC_VERSION you're using (e.g., 
  - If you're relying on loading it from .nvmrc or .node-version, you need to configure `legacy_version_file` on your asdf install
- You're running the command outside of a repository and never defined a global package version so asdf knows which node version to default to (e.g., `asdf global nodejs SEMANTIC_VERSION`)

I wrote a [comment] that explains a little about how the shims work, but beyond that there is not enough information here to help you.

If you're still stuck, recommend reviewing the [README] and asdf website docu closely.

[install instructions]: https://asdf-vm.com/guide/getting-started.html#_3-install-asdf
[comment]: https://github.com/asdf-vm/asdf/issues/1656#issuecomment-2257322800
[README]: https://github.com/asdf-vm/asdf-nodejs?tab=readme-ov-file#configuration

**Comment by augustobmoura** [comment]
> I have no idea on how to fix that, but no matter what version of Node.js I install, I can't run node because I always receive this message:
> 
> ```shell
> $ node --version
> node: symbol lookup error: node: undefined symbol: _ZN6icu_738ByteSink15GetAppendBufferEiiPciPi
> ```
> 
> Any help will be appreciated!

Do you have the same problem installing NodeJS from [the official distribution](https://nodejs.org/), or is this a specific problem to asdf-nodejs?

Can you also send the output of the `asdf info` command?

**Comment by kemelzaidan** [comment]
Hello, thanks for all the help. After looking for an answer for some time, I found that the problem was in the `node-gyp` package. I had to clean it up and reinstall it. Thanks for the help, once again
